name: "Build gradle"

on: ['push']

jobs:
  build-jar:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Gradle | Build
        run: .github-package-registry-gradle/gradlew build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}